config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # resources :lectures do
  #   member do
  #     get '/lectures/new'=> 'lectures#new'
  #     end
  # end
  resources :courses do |course|
    resources :lectures, :except =>[:index] do
      resources :comments, :except =>[:new, :index,:show, :edit]
    get '/lectures' => 'courses#show', as: :lectures_path
    member do
      put "like" => 'lectures#vote'
    end
    member do
      post "spam" => 'lectures#spam'
    end
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/'=>'courses#index'
  resources :users do
  #/users/:id/confirm_email
  member do
  get '/confirm_email'=> 'users#confirm_email' 
  end
  end
end

app/models/lecture.rb
class Lecture < ApplicationRecord
    acts_as_votable
    mount_uploader :attachment, AttachmentUploader
    belongs_to :course
    has_many :comments, dependent: :destroy
    has_many :spams
    has_many :users, :through => :spams
    
end

app/controllers/lectures_controller.rb
class LecturesController < InheritedResources::Base
  before_action :authenticate_user!
  layout 'nav'

  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
    flash[:warning] = exception.message
    redirect_to courses_url
  end
  respond_to :js, :json, :html
  def new
    @course = Course.find(params[:course_id])
    @lecture = Lecture.new
  end
  def create
    @course = Course.find(params[:course_id])
    @lecture = @course.lectures.new(lecture_params)
    @lecture.save
  

    redirect_to course_url(@course.id)
  end
  def edit
    @course = Course.find(params[:course_id])
   
  end
  def show
    @course = Course.find(params[:course_id])
    @lecture = Lecture.find(params[:id])
   
    @comment= Comment.new
  end

  def update
    @course = Course.find(params[:course_id])
    @lecture = Lecture.find(params[:id])
   @lecture.update lecture_params
   redirect_to course_lecture_url(@course.id, @lecture.id)
  end
  def destroy
    @course = Course.find(params[:course_id])
    @lecture = Lecture.find(params[:id])
    @lecture.destroy
   redirect_to course_url(@course.id)
  end

  def vote
    if !current_user.liked? @lecture
      @lecture.liked_by current_user
    elsif current_user.liked? @lecture
      @lecture.unliked_by current_user
    end
  end

  def spam
    @course = Course.find(params[:course_id])
    @lecture = Lecture.find(params[:id])
    @spam= Spam.where("user_id ="+current_user.id.to_s+" AND lecture_id ="+ @lecture.id.to_s)
    if !@spam.any? 
      @spam = Spam.new({:user_id =>current_user.id, :lecture_id => @lecture.id})
      @spam.save
      flash[:spam]="Marked as spam"
    else
      flash[:spam]= "Already marked as spam"
    end 
    redirect_to course_lecture_url(@course.id, @lecture.id)
  end
  private

    def lecture_params
      params.require(:lecture).permit(:content, :attachment)
    end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.erb
<%= form_with(model: [@course,lecture], local: true) do |form| %>
  <% if lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :content %><br/>
    <%= form.text_area :content, :class => 'ckeditor form-control'  ,rows: 5, id: :lecture_content %>
  </div>

  <div class="field  form-group">
    <%= form.label :attachment %>
    <%= form.file_field :attachment, id: :lecture_attachment %>
  </div>

  <div class="actions text-center form-group">
    <%= form.submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Show', course_lecture_path(@course,@lecture) %> |
<%= link_to 'Back', course_lecture_path(@course,@lecture) %>

app/views/lectures/new.html.erb
<h1 class="text-center alert alert-info"><%= @course.title%></h1>
<h2 class="text-center">New Lecture</h2>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Back', courses_path %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>



<div class="page-header">
<h1><%=@course.title%></h1>
<% i=1%>
<% @course.lectures.each do |lecture| %>
<% if(lecture.id == @lecture.id)%>
  <h2>Lecture <%=i%> </h2>
  <%end%>
<%i+=1%>
  <%end%>
  <h3>Content:</h3>
  <p> <%= @lecture.content %></p>
  <h3>Attachment:</h3>
  <p>   <%= link_to "uploads/lecture/attachment/"+@lecture.id.to_s+"/"+@lecture.attachment.to_s, @lecture.attachment.to_s, :target=> "_blank" %></p>
</div>
<div class="row">
<div class="col-xs-6">
<div class="col-xs-3">
<%= link_to like_course_lecture_path(@course,@lecture), class:"", method: :put, remote: :true do %>
  <span class=" like_btn glyphicon glyphicon-thumbs-up">
  </span>
  <%end%>
  <span class="likes_count">
  <%= @lecture.get_upvotes.size%>
  </span>
  </div>
  <div class="class="col-xs-3">
  <%= link_to spam_course_lecture_path(@course,@lecture), method: :post do %>
  <span class="glyphicon glyphicon-flag"></span>
  <%end%>
  <span id="spam"><%= flash[:spam]%></span>
  </div>
 </div>
 </div>
<h3>Comments:</h3>
  <% i=1%>
  <% @lecture.comments.each do |comment| %>
  <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%=comment.user.name%></h3>
  </div>
  <div class="panel-body">
  <div class="row">
  <div class="col-xs-12">
  <div class="col-xs-6">
  <%=comment.text%> 
  </div> 
  <div class="col-xs-6">
  <% if(comment.user.id == current_user.id) %>
  <%= link_to course_lecture_comment_url(@course.id,@lecture.id,comment.id), method: :delete, data: { confirm: 'Are you sure?' } do %>
  <button type="button" class="btn btn-danger">Delete Comment</button>
  <%end%>
  <% end %> 
  </div>
  </div>
  </div>
  </div>
  <div class="panel-footer"><%=comment.updated_at%></div>
</div>
<% i+=1%>
  <% end %> 
<%= render 'comments/form', comment: @comment %>
<br/>

<div class="row">
<div class="col-xs-6">
<div class="col-xs-3">
<% if can? :update, Lecture %>
<%= link_to edit_course_lecture_path(@course.id, @lecture.id) do%>
  <button type="button" class="btn btn-primary"> Edit Lecture</button>
<%end%>
<%end%>
</div>
<div class="col-xs-3">
<% if can? :destroy, Lecture %>
<%= link_to course_lecture_url, method: :delete, data: { confirm: 'Are you sure?' } do %>
  <button type="button" class="btn btn-danger">Delete Lecture</button>
<%end%>
<%end%>
</div>
</div>
</div>

<br/>
<%= link_to 'Back', course_url(@course.id) %>
<script>


</script>

app/views/lectures/vote.js.erb
<% if(current_user.liked? @lecture)%>
 $(".likes_count").html("<%=@lecture.get_upvotes.size%>"); 
$(".like_btn").addClass('liked');
<% else %>
$(".likes_count").html("<%=@lecture.get_upvotes.size%>"); 
$(".like_btn").removeClass('liked');
<% end %>