config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # resources :lectures do
  #   member do
  #     get '/lectures/new'=> 'lectures#new'
  #     end
  # end
  resources :courses do |course|
    resources :lectures, :except =>[:index] do
      resources :comments, :except =>[:new, :index,:show, :edit]
    get '/lectures' => 'courses#show', as: :lectures_path
    member do
      put "like" => 'lectures#vote'
    end
    member do
      post "spam" => 'lectures#spam'
    end
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/'=>'courses#index'
  resources :users do
  #/users/:id/confirm_email
  member do
  get '/confirm_email'=> 'users#confirm_email' 
  end
  end
end

app/controllers/courses_controller.rb
class CoursesController < InheritedResources::Base
  before_action :authenticate_user!
  layout 'nav'
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
    flash[:warning] = exception.message
    redirect_to courses_url
  end
  
  private

    def course_params
      params.require(:course).permit(:title)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field text-center">
    <%= form.label :title %>
    <%= form.text_field :title, id: :course_title %>
  </div>

  <div class="actions text-center">

    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @courses.each do |course| %>
      <tr>
        <td style="font-size:16px"><strong><%= course.title %><strong></td>
        <td><%= link_to  course do%>
          <button type="button" class="btn btn-info">Show Course</button>
          <%end%>
          </td>
        <% if can? :update, Course %>
        <td><%= link_to  edit_course_path(course) do%>
          <button type="button" class="btn btn-primary"> Edit course title</button>
          <%end%>
          </td>
        <% end %>
        <% if can? :destroy, Course %>
        <td><%= link_to course, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <button type="button" class="btn btn-danger">Delete whole course</button>
        <%end%>
        </td>
        <% end %> 
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% if can? :create, Course %>
<%= link_to  new_course_path do %>
  <div class="text-center"><button type="button" class="btn btn-primary">New Course</button></div>
<% end %>
<% end %>

app/views/courses/new.html.erb
<h1 class="text-center">New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <strong>Title:</strong>
  <%= @course.title %>
  <% if can? :update, Lecture %>
<%= link_to  edit_course_path(@course) do%> 
  <button type="button" class="btn btn-primary"> Edit course title</button>
  <%end%>
<%end%>
</h2>
<% i=1%>
<table class="table">
<% @course.lectures.each do |lecture| %>

  <tr>
  <th>Lecture <%=i%> </th>
  </tr>
  <tr>
  <td><%= lecture.content %></td>
  <td><%= link_to  course_lecture_url(@course.id, lecture.id) do%>
    <button type="button" class="btn btn-info">Display lecture</button>
    <%end%>
    </td>
  </tr>
  
<% i+=1%>
  <% end %>  
  </table>
</p>
<% if can? :create, Lecture %>
<%= link_to new_course_lecture_path(@course) do%>
  <div class="text-center"> <button class="btn btn-primary">New Lecture</btn></div>
  <%end%>
<% end %>

<br/>
<%= link_to 'Back', courses_path %>