config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # resources :lectures do
  #   member do
  #     get '/lectures/new'=> 'lectures#new'
  #     end
  # end
  resources :courses do |course|
    resources :lectures, :except =>[:index] do
      resources :comments, :except =>[:new, :index,:show, :edit]
    get '/lectures' => 'courses#show', as: :lectures_path
    member do
      put "like" => 'lectures#vote'
    end
    member do
      post "spam" => 'lectures#spam'
    end
    end
  end

  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/'=>'courses#index'
  resources :users do
  #/users/:id/confirm_email
  member do
  get '/confirm_email'=> 'users#confirm_email' 
  end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MOOC</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'jquery', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/nav.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MOOC</title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'jquery', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-brand" href="#">MOOC</div>
  </div>
    <ul class="nav navbar-nav navbar-right">
    
     <p class="navbar-text navbar-right">Signed in as <%=current_user.name%></p>
    <li>
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
   </li>
   <li><%= link_to new_admin_user_session_path do %>
    Admin Panel
  <% end %></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
    <%= yield %>
  </body>
</html>